name: Scan Docker Image in GHCR

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  scan-docker-image:
    name: Trivy Scan Docker Image
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Scan Docker Image with Trivy Action
      uses: aquasecurity/trivy-action@0.28.0
      with:
        scan-type: 'fs' # Replace with your image name
        format: "template" # Use Go template format for output
        template: "@trivy-format.tmpl" # Path to the Go template file
        output: "trivy_report.json"

    - name: Display CVE Report
      run: |
        echo "CVE Report:" && cat trivy_report.json

    - name: Upload CVE Report to API
      run: |
          # Make a POST request with the CVE report
          curl -X POST -H "Content-Type: application/json" --data @trivy_report.json "http://212.227.96.139:8080/api/v1/vulnerabilities"

    - name: Confirm Upload
      run: echo "CVE report uploaded successfully"
